language: node_js
node_js:
  - "4.3"
  - "5"
  - "6"
script:
  - npm test
  - npm run typecheck
addons:
  code_climate:
    repo_token: 2fd179f60745c90117aede240974f8d63c085b39e4af6a4364e70a1f9d0ee029
